[project]
name = "progress-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Venkatesh Panyam", email = "whenkatezh@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "torch>=2.14.0",
]

[project.scripts]
progress-1 = "progress_1:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
